#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTestMailSender
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MailsAndSenders")]
	public partial class EmailsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertEmail(Email instance);
    partial void UpdateEmail(Email instance);
    partial void DeleteEmail(Email instance);
    partial void InsertLetter(Letter instance);
    partial void UpdateLetter(Letter instance);
    partial void DeleteLetter(Letter instance);
    partial void InsertMessage(Message instance);
    partial void UpdateMessage(Message instance);
    partial void DeleteMessage(Message instance);
    #endregion
		
		public EmailsDataContext() : 
				base(global::WpfTestMailSender.Properties.Settings.Default.MailsAndSendersConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public EmailsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmailsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmailsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmailsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Email> Email
		{
			get
			{
				return this.GetTable<Email>();
			}
		}
		
		public System.Data.Linq.Table<Letter> Letter
		{
			get
			{
				return this.GetTable<Letter>();
			}
		}
		
		public System.Data.Linq.Table<Message> Message
		{
			get
			{
				return this.GetTable<Message>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Email")]
	public partial class Email : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Adress;
		
		private string _Name;
		
		private EntitySet<Letter> _Letter;
		
		private EntitySet<Letter> _Letter1;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAdressChanging(string value);
    partial void OnAdressChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Email()
		{
			this._Letter = new EntitySet<Letter>(new Action<Letter>(this.attach_Letter), new Action<Letter>(this.detach_Letter));
			this._Letter1 = new EntitySet<Letter>(new Action<Letter>(this.attach_Letter1), new Action<Letter>(this.detach_Letter1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adress", DbType="NChar(100)")]
		public string Adress
		{
			get
			{
				return this._Adress;
			}
			set
			{
				if ((this._Adress != value))
				{
					this.OnAdressChanging(value);
					this.SendPropertyChanging();
					this._Adress = value;
					this.SendPropertyChanged("Adress");
					this.OnAdressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Email_Letter", Storage="_Letter", ThisKey="Id", OtherKey="id_RecipientEmail")]
		public EntitySet<Letter> Letter
		{
			get
			{
				return this._Letter;
			}
			set
			{
				this._Letter.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Email_Letter1", Storage="_Letter1", ThisKey="Id", OtherKey="id_SenderEmail")]
		public EntitySet<Letter> Letter1
		{
			get
			{
				return this._Letter1;
			}
			set
			{
				this._Letter1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Letter(Letter entity)
		{
			this.SendPropertyChanging();
			entity.RecipientEmail = this;
		}
		
		private void detach_Letter(Letter entity)
		{
			this.SendPropertyChanging();
			entity.RecipientEmail = null;
		}
		
		private void attach_Letter1(Letter entity)
		{
			this.SendPropertyChanging();
			entity.SenderEmail = this;
		}
		
		private void detach_Letter1(Letter entity)
		{
			this.SendPropertyChanging();
			entity.SenderEmail = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Letter")]
	public partial class Letter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _id_RecipientEmail;
		
		private int _id_Message;
		
		private System.Nullable<System.DateTime> _Date_Send;
		
		private int _id_SenderEmail;
		
		private EntityRef<Email> _Email;
		
		private EntityRef<Email> _Email1;
		
		private EntityRef<Message> _Message;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_RecipientEmailChanging(int value);
    partial void Onid_RecipientEmailChanged();
    partial void Onid_MessageChanging(int value);
    partial void Onid_MessageChanged();
    partial void OnDate_SendChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_SendChanged();
    partial void Onid_SenderEmailChanging(int value);
    partial void Onid_SenderEmailChanged();
    #endregion
		
		public Letter()
		{
			this._Email = default(EntityRef<Email>);
			this._Email1 = default(EntityRef<Email>);
			this._Message = default(EntityRef<Message>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_RecipientEmail", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_RecipientEmail
		{
			get
			{
				return this._id_RecipientEmail;
			}
			set
			{
				if ((this._id_RecipientEmail != value))
				{
					if (this._Email.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_RecipientEmailChanging(value);
					this.SendPropertyChanging();
					this._id_RecipientEmail = value;
					this.SendPropertyChanged("id_RecipientEmail");
					this.Onid_RecipientEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Message", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_Message
		{
			get
			{
				return this._id_Message;
			}
			set
			{
				if ((this._id_Message != value))
				{
					if (this._Message.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_MessageChanging(value);
					this.SendPropertyChanging();
					this._id_Message = value;
					this.SendPropertyChanged("id_Message");
					this.Onid_MessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Send", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_Send
		{
			get
			{
				return this._Date_Send;
			}
			set
			{
				if ((this._Date_Send != value))
				{
					this.OnDate_SendChanging(value);
					this.SendPropertyChanging();
					this._Date_Send = value;
					this.SendPropertyChanged("Date_Send");
					this.OnDate_SendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_SenderEmail", DbType="Int NOT NULL")]
		public int id_SenderEmail
		{
			get
			{
				return this._id_SenderEmail;
			}
			set
			{
				if ((this._id_SenderEmail != value))
				{
					if (this._Email1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_SenderEmailChanging(value);
					this.SendPropertyChanging();
					this._id_SenderEmail = value;
					this.SendPropertyChanged("id_SenderEmail");
					this.Onid_SenderEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Email_Letter", Storage="_Email", ThisKey="id_RecipientEmail", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Email RecipientEmail
		{
			get
			{
				return this._Email.Entity;
			}
			set
			{
				Email previousValue = this._Email.Entity;
				if (((previousValue != value) 
							|| (this._Email.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Email.Entity = null;
						previousValue.Letter.Remove(this);
					}
					this._Email.Entity = value;
					if ((value != null))
					{
						value.Letter.Add(this);
						this._id_RecipientEmail = value.Id;
					}
					else
					{
						this._id_RecipientEmail = default(int);
					}
					this.SendPropertyChanged("RecipientEmail");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Email_Letter1", Storage="_Email1", ThisKey="id_SenderEmail", OtherKey="Id", IsForeignKey=true)]
		public Email SenderEmail
		{
			get
			{
				return this._Email1.Entity;
			}
			set
			{
				Email previousValue = this._Email1.Entity;
				if (((previousValue != value) 
							|| (this._Email1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Email1.Entity = null;
						previousValue.Letter1.Remove(this);
					}
					this._Email1.Entity = value;
					if ((value != null))
					{
						value.Letter1.Add(this);
						this._id_SenderEmail = value.Id;
					}
					else
					{
						this._id_SenderEmail = default(int);
					}
					this.SendPropertyChanged("SenderEmail");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Message_Letter", Storage="_Message", ThisKey="id_Message", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Message Message
		{
			get
			{
				return this._Message.Entity;
			}
			set
			{
				Message previousValue = this._Message.Entity;
				if (((previousValue != value) 
							|| (this._Message.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Message.Entity = null;
						previousValue.Letter.Remove(this);
					}
					this._Message.Entity = value;
					if ((value != null))
					{
						value.Letter.Add(this);
						this._id_Message = value.id;
					}
					else
					{
						this._id_Message = default(int);
					}
					this.SendPropertyChanged("Message");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Message")]
	public partial class Message : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _text;
		
		private string _subject;
		
		private EntitySet<Letter> _Letter;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void OnsubjectChanging(string value);
    partial void OnsubjectChanged();
    #endregion
		
		public Message()
		{
			this._Letter = new EntitySet<Letter>(new Action<Letter>(this.attach_Letter), new Action<Letter>(this.detach_Letter));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string subject
		{
			get
			{
				return this._subject;
			}
			set
			{
				if ((this._subject != value))
				{
					this.OnsubjectChanging(value);
					this.SendPropertyChanging();
					this._subject = value;
					this.SendPropertyChanged("subject");
					this.OnsubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Message_Letter", Storage="_Letter", ThisKey="id", OtherKey="id_Message")]
		public EntitySet<Letter> Letter
		{
			get
			{
				return this._Letter;
			}
			set
			{
				this._Letter.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Letter(Letter entity)
		{
			this.SendPropertyChanging();
			entity.Message = this;
		}
		
		private void detach_Letter(Letter entity)
		{
			this.SendPropertyChanging();
			entity.Message = null;
		}
	}
}
#pragma warning restore 1591
